MCOP-55 - don't treat empty results as though they're not empty
Array#max on an empty array will return nil, which then will cause
the error:

    undefined method `+' for nil:NilClass (NoMethodError)

Here we gate the results processing on getting a populated results
set.